name: Pass the artifact

on: [workflow_dispatch]
    inputs:
      name:
        description: 'File Name'
        required: fale

jobs:
  job_1:
    name: Create File
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: |
          echo "Hello World" > hello.txt
      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: hello.txt

jobs:
 greet:
 runs-on: ubuntu-latest
 steps:
 - name: Send greeting
 run: echo "Hello ${{ github.event.inputs.name }}"
